### PR TITLE
added option for prefix only highlighting

### PR DESCRIPTION
**Pull request by mscolnick**

### CODE REVIEW

**Comment by julmot** [comment]
@mscolnick You might be interested in [jquery.mark](https://github.com/julmot/jquery.mark) which has an option `wordBoundary` to fit this requirement.

**Comment by andrew-y0u** [comment]
I'm sorry, don't know where to write...
We can to show words which not match/not found?

**Comment by julkue** [comment]
@andrew-y0u Can you please explain what you mean and what your use case is?

**Comment by andrew-y0u** [comment]
@julmot I have a list of words. I need highlight this words in text and I need displaying words which not found.

Example:
array of words which need to find:  ['word1', 'word2', 'word3'];
text where I must find: "lorem ipsum word1 lorem word2";

I must highlight 'word1' and 'word2', and pass  'word3' to new array with words which not found, so then I can display not found words.

**Comment by julkue** [comment]
@andrew-y0u I'm giving you an example with [mark.js](https://markjs.io/):

https://jsfiddle.net/julmot/qp44591x/

If you want you can [open a feature request](https://github.com/julmot/jquery.mark/issues/new) to implement an option for this.

**Comment by julmot** [comment]
@andrew-y0u Did this solve your issue?

**Comment by julkue** [comment]
@andrew-y0u Good news! I just released [v6.1.0](https://github.com/julmot/mark.js/releases/tag/6.1.0) of [mark.js](https://markjs.io/) containing a new callback option `noMatch`, which will receive not found terms. This solves your issue.

**Pull request closed without merging**
